* My personal emacs configuration

** INSTALLATION
#+NAME: install
#+BEGIN_SRC
mkdir ~/.emacs.d
git clone https://github.com/9ziggy9/my_emacs ~/.emacs.d
#+END_SRC

** NOTES
**** I use Nerd Fonts, visit their repo for installation directions, or simply change font choice in init.el.
**** In order to use LSP mode with React/JSX projects, you need to install and init eslint in $HOME directory
#+BEGIN_SRC
cd ~
npm init
npm install -g eslint babel-eslint eslint-plugin-react
eslint --init
#+END_SRC
EDIT: eslint config continues to be an annoying uphill battle. I think I need to configure flycheck or lsp-mode to default to root eslint file. For now, one can get a project up and running by simply running
#+BEGIN_SRC
eslint --init
#+END_SRC
in a project directory. I suppose this makes sense, as we will likely want different configuration settings depending on project.
**** In case a project is ever blacklisted, you will want to run the following
#+BEGIN_SRC
M-x lsp-workspace-blacklist-remove
#+END_SRC

** RESOURCES
   SystemCrafter videos, obviously, some code stolen from Tsoding Daily. Helpful config walkthrough, where I stole web dev stuff:
   https://jamiecollinson.com/blog/my-emacs-config/
   https://github.com/daviwil/emacs-from-scratch
